#!/bin/sh
# source this file
color=$( $HOME/bin/ps1.py )

PS1='${debian_chroot:+($debian_chroot)}\[\e[00;35m\][\t]\[\e[00m\] \
\[\e[01;3${color}m\]\u@\h\[\e[00m\]\
\[\e[01;33m\]$(__git_ps1)\[\e[00m\]\
:\[\e[01;34m\]\w\[\e[00m\]\r\n\$ '
