#!/bin/sh
# source this file

export PATH="$HOME/bin:$PATH"
export PATH="$PATH:/usr/lib/google-cloud-sdk/bin"

# Local pip installed packages (e.g. pip install --user pants)
export PATH="$HOME/.local/bin:$PATH"
