#!/bin/sh
# alias vi='vim -p'
# alias vim='vim -p'
# alias view='view -p'
# alias gvim='v'
alias rsync='rsync --progress'
alias rm='rm -I'
alias blaze='bazel'
alias mv='mv -i'
alias cp='cp -i --reflink=auto  --sparse=always'

function bd() {
  curdir="$PWD"
  while [ "$curdir" != "/" ] ; do
    if [ -d "${curdir}/.git" ] ; then
      cd $curdir
      break
    fi
    curdir=$( dirname "$curdir" )
  done
}

function new() {
  ls -lrt | tail -n 15
}

